[2010-10-15 18:51:21,156] [INFO] from connect in work at work.py:136 :
connection established

[2010-10-15 18:53:03,992] [ERROR] from read in snc at snc.py:114 :
failed to read:
error('SSL error [func SSL_read] [errno: Success]: error:00000006:lib(0):func(0):EVP lib',)

[2010-10-15 18:53:03,992] [ERROR] from connect in work at work.py:236 :
failed to communicate with orzoj-server because of network error

[2010-10-15 18:53:03,993] [ERROR] from run_judge in main at main.py:76 :
error occurred, terminating program


