[2010-10-15 17:23:43,135] [INFO] from run_server in main at main.py:69 :
orzoj-server started, listening on 9351

[2010-10-15 17:23:44,526] [INFO] from run_server in main at main.py:82 :
connected by '127.0.0.1:52840'

[2010-10-15 17:23:45,383] [INFO] from run in work at work.py:397 :
[judge 'orzoj-judge-default'] successfully connected

[2010-10-15 17:23:50,564] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #64

[2010-10-15 17:23:50,653] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'a+b'

[2010-10-15 17:24:53,840] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #65

[2010-10-15 17:24:53,887] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'a+b'

[2010-10-15 17:24:58,518] [WARNING] from _read in web at web.py:242 :
website requests relogin

[2010-10-15 17:27:28,499] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #66

[2010-10-15 17:27:28,522] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'a+b'

[2010-10-15 17:28:11,736] [DEBUG] from _thread_fetch_task in work at work.py:69 :
fetched task #67

[2010-10-15 17:28:11,772] [INFO] from _solve_task in work at work.py:214 :
[judge 'orzoj-judge-default'] received task for problem u'a+b'

[2010-10-15 17:28:23,951] [WARNING] from _read in web at web.py:242 :
website requests relogin

[2010-10-15 17:29:35,433] [INFO] from sig_handler in control at control.py:45 :
reveived signal 2, terminating...

[2010-10-15 17:29:35,433] [ERROR] from accept in snc at snc.py:78 :
socket error: error(4, 'Interrupted system call')

[2010-10-15 17:29:35,434] [DEBUG] from run_server in main at main.py:88 :
waiting for threads, current active count: 4

[2010-10-15 17:29:35,434] [DEBUG] from run_server in main at main.py:90 :
active thread: 'MainThread'

[2010-10-15 17:29:35,435] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work.thread_work'

[2010-10-15 17:29:35,435] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work.thread_new_judge_connection'

[2010-10-15 17:29:35,436] [DEBUG] from run_server in main at main.py:90 :
active thread: 'work._thread_fetch_task'

